# Generated by Django 4.2.9 on 2024-08-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_alter_author_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='О книге')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Ссылка')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('on_hand', models.BooleanField(default=False, verbose_name='На руках')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'books',
            },
        ),
    ]
