# Generated by Django 4.2.9 on 2024-08-11 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='lending_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
