# Generated by Django 4.2.9 on 2024-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0002_alter_lending_lending_date_alter_lending_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
